#ifndef VGA_COLORS_H
#define VGA_COLORS_H

// COLORS
#define BG_BLACK_FG_BLACK 0X00
#define BG_BLACK_FG_DBLUE  0X01
#define BG_BLACK_FG_DGREEN  0X02
#define BG_BLACK_FG_DCYAN  0X03
#define BG_BLACK_FG_DBROWN  0X04
#define BG_BLACK_FG_DPINK  0X05
#define BG_BLACK_FG_BROWN  0X06
#define BG_BLACK_FG_LGREY  0X07
#define BG_BLACK_FG_GREY  0X08
#define BG_BLACK_FG_PURPLE  0X09
#define BG_BLACK_FG_LGREEN  0X0a
#define BG_BLACK_FG_CYAN  0X0b
#define BG_BLACK_FG_ORANGE  0X0c
#define BG_BLACK_FG_PINK  0X0d
#define BG_BLACK_FG_YELLOW  0X0e
#define BG_BLACK_FG_WHITE  0X0f

#define BG_WHITE_FG_BLACK 0xf0

#endif